# Generated by Django 4.2 on 2023-05-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_direction_history_partner_project_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Подуслуга',
                'verbose_name_plural': 'Подуслуги',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.TextField(default='Услуга', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.service', verbose_name='Услуга'),
        ),
    ]
