# Generated by Django 4.2 on 2023-05-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_subservice_delete_project_service_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_address', models.CharField(max_length=200)),
                ('phone_numbers', models.CharField(max_length=200)),
                ('email_addresses', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_services', to='server.service', verbose_name='Услуга'),
        ),
    ]
