# Generated by Django 4.2 on 2023-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_contact_alter_subservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='postal_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_addresses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.JSONField(default=list),
        ),
    ]
